# Generated by Django 5.2.1 on 2025-05-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='cancelamentos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alterações/Cancelamentos'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='origem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Origens'),
        ),
    ]
